version: '3'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    ports:
      - 33066:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8060:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - mynetwork

networks:
  mynetwork:
